version: "3.9"
services:
  api:
    build: ./src/resume_parser
    container_name: resume_parser
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - RESUME_OUTPUT_DIR=/app/resumes
      - WEAVIATE_URL=http://weaviate:8080
    volumes:
      - ./src/resume_parser:/app
      - ./resumes:/app/resumes
    depends_on:
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
 