# Use Node LTS
FROM node:lts-slim

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the app
COPY . .
# Define arguments for build runtime
ARG NEXT_CLERK_PUBLIC_PUBLISHABLE_KEY
ARG NEXT_CLERK_SECRET_KEY

# Set environment variables
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_CLERK_PUBLIC_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$NEXT_CLERK_SECRET_KEY

# Build Next.js
RUN npm run build

# Expose port
EXPOSE 3000

# Start Next.js in production mode
CMD ["npm", "run", "start"]
